# Generated by Django 2.2.5 on 2019-09-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Representative',
        ),
    ]
